Description of get_variable_file_path
Home > timevp-main > timevp-main > timevp_lib > get_variable_file_path.m
get_variable_file_path
PURPOSE
Returns the complete file path based on a subject and
SYNOPSIS
function variable_file = get_variable_file_path(sub_id, var_name)
DESCRIPTION
 Returns the complete file path based on a subject and
 variable.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_variable_data Return subject_id and variable_name of variable
has_variable Returns true if the variable file exists in that subj's dir.
save_variable_data Saves data to specified location with: data_filepath = '';
timevp_extract_pairs_by_subject Extracts pairs of events for a specific subject that fit a specified temporal condition
SOURCE CODE
function variable_file = get_variable_file_path(sub_id, var_name)
% Returns the complete file path based on a subject and
% variable.
[~, dir_dataset] = timevp_config_dataset_info();
variable_file = fullfile(dir_dataset, int2str(sub_id), sprintf('%s.csv', var_name));