Description of has_variable
Home > timevp-main > timevp-main > timevp_lib > has_variable.m
has_variable
PURPOSE
Returns true if the variable file exists in that subj's dir.
SYNOPSIS
function has_it = has_variable(subject_id, var_name)
DESCRIPTION
Returns true if the variable file exists in that subj's dir.
   has_variable(SUBJECT_ID, VARIABLE_NAME)
   Searches the data/subject_id subdirectory of the subject data associated with
   the given numerical subject ID, and sees if a csv or mat file containing
   the given variable exists.  If so, returns 1, if not, returns 0.
CROSS-REFERENCE INFORMATION
This function calls:
get_variable_file_path Returns the complete file path based on a subject and
This function is called by:
get_variable_data Return subject_id and variable_name of variable
save_variable_data Saves data to specified location with: data_filepath = '';
timevp_construct_temporal_profile Generates temporal profile of a group of continue variables
timevp_extract_pairs_by_subject Extracts pairs of events for a specific subject that fit a specified temporal condition
SOURCE CODE
function has_it = has_variable(subject_id, var_name)
%Returns true if the variable file exists in that subj's dir.
%   has_variable(SUBJECT_ID, VARIABLE_NAME)
%
%   Searches the data/subject_id subdirectory of the subject data associated with
%   the given numerical subject ID, and sees if a csv or mat file containing
%   the given variable exists.  If so, returns 1, if not, returns 0.
variable_file = get_variable_file_path(subject_id, var_name);
has_it = exist(variable_file, 'file') == 2;
end