Description of save_variable_data
Home > timevp-main > timevp-main > timevp_lib > save_variable_data.m
save_variable_data
PURPOSE
Saves data to specified location with: data_filepath = '';
SYNOPSIS
function data_filepath = save_variable_data(subject_id, variable_name, data)
DESCRIPTION
  Saves data to specified location with: data_filepath = '';
CROSS-REFERENCE INFORMATION
This function calls:
get_variable_file_path Returns the complete file path based on a subject and
has_variable Returns true if the variable file exists in that subj's dir.
write2csv Write data to specified csv file
This function is called by:
SOURCE CODE
function data_filepath = save_variable_data(subject_id, variable_name, data)
%  Saves data to specified location with: data_filepath = '';
if isempty(data)
    error('Input data is empty. Cannot save empty data to csv files.');
%     return;
end
if has_variable(subject_id, variable_name)
    warning('Subject %d already save data file %s.csv. It will be replaced with the new file.', ...
        subject_id, variable_name);
end
data_filepath = get_variable_file_path(subject_id, variable_name);
write2csv(data, data_filepath);