Description of stream2event
Home > timevp-main > timevp-main > timevp_lib > stream2event.m
stream2event
PURPOSE
Convert stream data to cevent data
SYNOPSIS
function result = stream2event(stream, sample_rate, include_zero)
DESCRIPTION
 Convert stream data to cevent data
 cevent = cstream2cevent(stream, include_zero)
 stream - (input)category stream. list of pair [timestamp categorynumber]
               e.g.
               344.7000   32.0000
               344.8000   34.0000
               344.9000   34.0000
               345.0000   34.0000
               345.1000   34.0000
               345.2000   34.0000
               345.3000   34.0000
               345.4000   32.0000
               345.5000   32.0000
               345.6000   32.0000
 include_zero: a flag determing whether 0 segments should be treated as events
 or not. include_zero == 0 means not including 0 events, which is the
 default.
 cevent: (output)category event. list of [start_time end_time categorynumber]
        344.7000   344.8000  32.0000
        344.8000   345.4000  34.0000
        345.4000   345.7000  32.0000
  This function is copied from Ikhyun's function
  make_cevent_from_cstream.   Feb 19,2009
  Last modified by txu@indiana.edu
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_data_by_subject This function fetches data by subject ID and variable name
stream_cal_stats Report various stypes of statistics of stream type data
timevp_compute_statistics Computes event distribution statistics of provided time series data
timevp_construct_temporal_profile Generates temporal profile of a group of continue variables
timevp_extract_pairs Extracts pairs of events that fit a specified temporal condition
visualize_streams Plotting function for visualizing temporal pattens
SOURCE CODE
function result = stream2event(stream, sample_rate, include_zero)
% Convert stream data to cevent data
%
% cevent = cstream2cevent(stream, include_zero)
%
% stream - (input)category stream. list of pair [timestamp categorynumber]
%               e.g.
%               344.7000   32.0000
%               344.8000   34.0000
%               344.9000   34.0000
%               345.0000   34.0000
%               345.1000   34.0000
%               345.2000   34.0000
%               345.3000   34.0000
%               345.4000   32.0000
%               345.5000   32.0000
%               345.6000   32.0000
% include_zero: a flag determing whether 0 segments should be treated as events
% or not. include_zero == 0 means not including 0 events, which is the
% default.
%
% cevent: (output)category event. list of [start_time end_time categorynumber]
%        344.7000   344.8000  32.0000
%        344.8000   345.4000  34.0000
%        345.4000   345.7000  32.0000
%
%  This function is copied from Ikhyun's function
%  make_cevent_from_cstream.   Feb 19,2009
%
%  Last modified by txu@indiana.edu
if isempty(stream)
    warning('Input events is empty. Return empty stream.');
    result = zeros(0, 3);
    return;
end
if size(stream, 2) ~= 2
    error('Input stream must be in this type of data structure: [timestamp category]');
end
if nargin < 2
    sample_rate = timevp_config_dataset_info();
end
len_stream = size(stream, 1);
result = nan(len_stream, 3);
if isempty(stream)
    warning('The input data stream is empty. Exit funciton.');
    return
end
if ~exist('include_zero', 'var')
    include_zero = false;
end
MULTIPLIER = 1.2;
gap = 0;
result(1, 1) = stream(1, 1);   % start timestamp
result(1, 3) = stream(1, 2);   % value
% end_time = result(1,1) + gap; % temporal end timestamp
idx = 1;
for i = 2:len_stream
    gap = stream(i,1) - stream(i-1,1);
    if gap > (sample_rate*MULTIPLIER) || stream(i,2) ~= stream(i-1,2)
        idx = idx + 1;
        result(idx-1,2) = stream(i-1,1) + sample_rate;
        result(idx,1) = stream(i,1);
        result(idx,3) = stream(i,2);
    end
end
result(idx,2) = max(result(idx,1) + gap, stream(end, 1) + gap);
result = result(1:idx,:);
if include_zero == 0 % not including 0 events
    nonzeros = result(:, 3) ~= 0;
    result = result(nonzeros, :);
end
% exclude NaN data
result = result(~isnan(result(:, 3)), :);